# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\datas_and_files\AAA_Dev\python\pyqt\Projects\Wiredo\UiFiles\congratulations.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_congratulations(object):
    def setupUi(self, congratulations):
        congratulations.setObjectName("congratulations")
        congratulations.resize(298, 169)
        self.centralwidget = QtWidgets.QWidget(congratulations)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.iknow = QtWidgets.QPushButton(self.centralwidget)
        self.iknow.setObjectName("iknow")
        self.gridLayout.addWidget(self.iknow, 5, 0, 1, 1)
        congratulations.setCentralWidget(self.centralwidget)

        self.retranslateUi(congratulations)
        QtCore.QMetaObject.connectSlotsByName(congratulations)

    def retranslateUi(self, congratulations):
        _translate = QtCore.QCoreApplication.translate
        congratulations.setWindowTitle(_translate("congratulations", "Congratulations!"))
        self.label.setText(_translate("congratulations", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Congratulations!</span></p></body></html>"))
        self.label_2.setText(_translate("congratulations", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Your require is accepted.</span></p></body></html>"))
        self.label_3.setText(_translate("congratulations", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Now you\'re one of us.</span></p></body></html>"))
        self.label_4.setText(_translate("congratulations", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">But at the same time,</span></p></body></html>"))
        self.label_5.setText(_translate("congratulations", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">you no longer belong to the outside world.</span></p></body></html>"))
        self.iknow.setText(_translate("congratulations", "I Know."))
