# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\datas_and_files\AAA_Dev\python\pyqt\Projects\Wiredo\UiFiles\requiredenied.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_passwordincorrect(object):
    def setupUi(self, passwordincorrect):
        passwordincorrect.setObjectName("passwordincorrect")
        passwordincorrect.resize(362, 127)
        self.centralwidget = QtWidgets.QWidget(passwordincorrect)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Goback = QtWidgets.QPushButton(self.centralwidget)
        self.Goback.setObjectName("Goback")
        self.gridLayout.addWidget(self.Goback, 1, 0, 1, 1)
        passwordincorrect.setCentralWidget(self.centralwidget)

        self.retranslateUi(passwordincorrect)
        QtCore.QMetaObject.connectSlotsByName(passwordincorrect)

    def retranslateUi(self, passwordincorrect):
        _translate = QtCore.QCoreApplication.translate
        passwordincorrect.setWindowTitle(_translate("passwordincorrect", "Require Denied."))
        self.label.setText(_translate("passwordincorrect", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">Your password is incorrect.</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ff0000;\">You do not have access to site3408.</span></p></body></html>"))
        self.Goback.setText(_translate("passwordincorrect", "Go back"))
