# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\datas_and_files\AAA_Dev\python\pyqt\Projects\Wiredo\UiFiles\Welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(362, 213)
        self.centralwidget = QtWidgets.QWidget(Welcome)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 3)
        self.Imnew = QtWidgets.QPushButton(self.centralwidget)
        self.Imnew.setMinimumSize(QtCore.QSize(0, 23))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.Imnew.setFont(font)
        self.Imnew.setObjectName("Imnew")
        self.gridLayout.addWidget(self.Imnew, 5, 0, 1, 1)
        self.Imamember = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.Imamember.setFont(font)
        self.Imamember.setObjectName("Imamember")
        self.gridLayout.addWidget(self.Imamember, 5, 1, 1, 1)
        self.Imastuff = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(10)
        self.Imastuff.setFont(font)
        self.Imastuff.setObjectName("Imastuff")
        self.gridLayout.addWidget(self.Imastuff, 5, 2, 1, 1)
        Welcome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Welcome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 22))
        self.menubar.setObjectName("menubar")
        self.menuNULL = QtWidgets.QMenu(self.menubar)
        self.menuNULL.setObjectName("menuNULL")
        Welcome.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(Welcome)
        self.actionSave.setObjectName("actionSave")
        self.actionDelete_permanently = QtWidgets.QAction(Welcome)
        self.actionDelete_permanently.setObjectName("actionDelete_permanently")
        self.menuNULL.addSeparator()
        self.menuNULL.addAction(self.actionSave)
        self.menuNULL.addAction(self.actionDelete_permanently)
        self.menubar.addAction(self.menuNULL.menuAction())

        self.retranslateUi(Welcome)
        self.Imnew.clicked.connect(self.label.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "Welcome to Site3408!"))
        self.label.setText(_translate("Welcome", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Welcome to Site-3408!</span></p></body></html>"))
        self.label_2.setText(_translate("Welcome", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">Come to Site-3408. Relax in its elegant holding rooms.</span></p></body></html>"))
        self.label_3.setText(_translate("Welcome", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">Resting in the shade of its multiple surveillance cameras.</span></p></body></html>"))
        self.label_4.setText(_translate("Welcome", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">Improve yourself in its world-class testing room. </span></p></body></html>"))
        self.label_5.setText(_translate("Welcome", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">Let\'s take care of everything.</span></p></body></html>"))
        self.Imnew.setText(_translate("Welcome", "I\'m new"))
        self.Imamember.setText(_translate("Welcome", "I\'m a member of Site-3408"))
        self.Imastuff.setText(_translate("Welcome", "I\'m a stuff"))
        self.menuNULL.setTitle(_translate("Welcome", "Save your progress"))
        self.actionSave.setText(_translate("Welcome", "Save"))
        self.actionDelete_permanently.setText(_translate("Welcome", "Delete permanently"))
