# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\datas_and_files\AAA_Dev\python\pyqt\Projects\Welcome_to_Site3408\UiFiles\Welcome_back.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeback(object):
    def setupUi(self, welcomeback):
        welcomeback.setObjectName("welcomeback")
        welcomeback.resize(529, 635)
        self.centralwidget = QtWidgets.QWidget(welcomeback)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setObjectName("next")
        self.verticalLayout.addWidget(self.next)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        welcomeback.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(welcomeback)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 25))
        self.menubar.setObjectName("menubar")
        self.menuSave_your_progress = QtWidgets.QMenu(self.menubar)
        self.menuSave_your_progress.setObjectName("menuSave_your_progress")
        welcomeback.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuSave_your_progress.menuAction())

        self.retranslateUi(welcomeback)
        QtCore.QMetaObject.connectSlotsByName(welcomeback)

    def retranslateUi(self, welcomeback):
        _translate = QtCore.QCoreApplication.translate
        welcomeback.setWindowTitle(_translate("welcomeback", "Welcome back."))
        self.label.setText(_translate("welcomeback", "<html><head/><body><p><img src=\":/3408.jpg\"/></p></body></html>"))
        self.label_2.setText(_translate("welcomeback", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Welcome back!We promise to provide you</span></p><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">with the most comfortable experience.</span></p></body></html>"))
        self.next.setText(_translate("welcomeback", "Next"))
        self.menuSave_your_progress.setTitle(_translate("welcomeback", "Save your progress"))
import resource_rc
